/****************************
* Carousel items.
* The file CaraouselItems.js is generated by create_pages.sh in the scripts folder.
* Use this file as a template in case you have to create it manually.
*/
Ext.define('9Pad.view.CarouselItems', {
  items: [
    {
      xtype : 'contentcard',
      backgroundImage: 'myContentCard1'
    },
    {
      xtype : 'contentcard',
      backgroundImage: 'myContentCard2'
    },
    {
      xtype : 'contentcard',
      backgroundImage: 'myContentCard3'
    },
    {
      xtype : 'contentcard',
      backgroundImage: 'myContentCard4'
    },
    {
      xtype : 'contentcard',
      backgroundImage: 'myContentCard5'
    },
    {
      xtype : 'contentcard',
      backgroundImage: 'myContentCard6'
    },
    {
      xtype : 'contentcard',
      backgroundImage: 'myContentCard7'
    },
    {
      xtype : 'contentcard',
      backgroundImage: 'myContentCard8'
    },
    {
      xtype : 'contentcard',
      backgroundImage: 'myContentCard9'
    },
    {
      xtype : 'contentcard',
      backgroundImage: 'myContentCard10'
    },
    {
      xtype : 'contentcard',
      backgroundImage: 'myContentCard11'
    },
  ]
})
