#!/bin/bash
# ============================================================================================
# Bash Shell Script for creation of carousel elements.
# Naming scheme for carousel elements: page<INDEX>.png where INDEX starts from 0.
# The script creates a style entry in cards.css for each carousel element found in the 
# resources/images folder.
# ============================================================================================

declare -r CONTENT_PATH=../client/9Pad/resources/images
declare -r CARDS_FILE=../client/9Pad/resources/css/cards.css
declare -r CAROUSEL_FILE=../client/9Pad/app/view/CarouselItems.js

echo "Creating $CARDS_FILE..."

echo "/****************************" > $CARDS_FILE
echo "* Carousel elements." >> $CARDS_FILE
echo "* This file is generated by create_pages.sh in the scripts folder." >> $CARDS_FILE
echo "*/" >> $CARDS_FILE

echo "Creating $CAROUSEL_FILE..."
echo "/****************************" > $CAROUSEL_FILE
echo "* Carousel items." >> $CAROUSEL_FILE
echo "* This file is generated by create_pages.sh in the scripts folder." >> $CAROUSEL_FILE
echo "*/" >> $CAROUSEL_FILE
echo "Ext.define('9Pad.view.CarouselItems', {" >> $CAROUSEL_FILE
echo "  items: [" >> $CAROUSEL_FILE


ls $CONTENT_PATH/page*.png | sed "s/.*\///" | sort -k 1.6 | while read F
do
  LEN=${#F}
  INDEX=${F:4:LEN-8}
   
  echo ".myContentCard$INDEX {" >> $CARDS_FILE
  echo "  background: url('../images/page$INDEX.png') no-repeat center;" >> $CARDS_FILE
  echo "}" >> $CARDS_FILE
  
  echo "    {" >> $CAROUSEL_FILE
  echo "      xtype : 'contentcard'," >> $CAROUSEL_FILE
  echo "      backgroundImage: 'myContentCard$INDEX'" >> $CAROUSEL_FILE
  echo "    }," >> $CAROUSEL_FILE
done

echo "  ]" >> $CAROUSEL_FILE
echo "})" >> $CAROUSEL_FILE

echo "done."
